---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: AWS IoT Greengrass component to pet your robocat fleet via subscription
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.pubsub:
        com.devopstar.Robocat:pubsub:1:
          policyDescription: Allows access to subscribe to devopstar/robocat/pet topic
          operations:
            - aws.greengrass#SubscribeToTopic
          resources:
            - devopstar/robocat/pet
Manifests:
- Name: Linux
  Platform:
    os: linux
  Artifacts:
    - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/greengrass-cicd.zip"
      Unarchive: ZIP
      Permission:
        Execute: ALL
        READ: ALL
  Lifecycle:
    Install:
      RequiresPrivilege: false
      Timeout: 600
      Script: |-
        pip3 install -r {artifacts:decompressedPath}/greengrass-cicd/requirements.txt
    Run:
      RequiresPrivilege: false
      Script: |-
        python3 {artifacts:decompressedPath}/greengrass-cicd/src/robocat.py
