---
RecipeFormatVersion: "2020-01-25"
ComponentName: com.devopstar.RobocatContainer
ComponentVersion: NEXT_PATCH
ComponentDescription: AWS IoT Greengrass component to pet your robocat fleet via subscription in a docker container
ComponentPublisher: Nathan Glover
ComponentDependencies:
  aws.greengrass.DockerApplicationManager:
    VersionRequirement: ~2.0.0
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ~2.0.0
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.pubsub:
        com.devopstar.RobocatContainer:pubsub:1:
          policyDescription: Allows access to publish to devopstar/robocat/+/meow topic
          operations:
            - aws.greengrass#PublishToTopic
            - aws.greengrass#SubscribeToTopic
          resources:
            - devopstar/robocat/*/meow
Manifests:
- Name: Linux
  Platform:
    os: linux
  Artifacts:
    - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/container.zip"
      Unarchive: ZIP
    - URI: "docker:536829251200.dkr.ecr.ap-southeast-2.amazonaws.com/robocatcontainer:latest"
  Lifecycle:
    Install:
      RequiresPrivilege: true
      Script: docker load -i {artifacts:decompressedPath}/container/container.tar
    Run:
      RequiresPrivilege: true
      Script: |-
        cat <<EOF > docker-compose.yml
        version: '3'

        services:
          robocatcontainer-pub:
            container_name: robocatcontainer-pub
            image: robocatcontainer
            command: robocat_pub.py
            environment:
              - SVCUID=${SVCUID}
              - AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT=${AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT}
              - AWS_IOT_THING_NAME=${AWS_IOT_THING_NAME}
            volumes:
              - {kernel:rootPath}/ipc.socket:{kernel:rootPath}/ipc.socket

          robocatcontainer-sub:
            container_name: robocatcontainer-sub
            image: 536829251200.dkr.ecr.ap-southeast-2.amazonaws.com/robocatcontainer:latest
            command: robocat_sub.py
            environment:
              - SVCUID=${SVCUID}
              - AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT=${AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT}
              - AWS_IOT_THING_NAME=${AWS_IOT_THING_NAME}
            volumes:
              - {kernel:rootPath}/ipc.socket:{kernel:rootPath}/ipc.socket
        EOF

        docker compose up
    Shutdown:
      RequiresPrivilege: true
      Script: |-
        docker compose down
    Recover:
      RequiresPrivilege: true
      Script: |-
        docker compose restart
