---
RecipeFormatVersion: "2020-01-25"
ComponentName: com.devopstar.RobocatContainer
ComponentVersion: NEXT_PATCH
ComponentDescription: AWS IoT Greengrass component to pet your robocat fleet via subscription in a docker container
ComponentPublisher: Nathan Glover
# ComponentDependencies:
#   aws.greengrass.DockerApplicationManager:
#     VersionRequirement: ~2.0.0
#   aws.greengrass.TokenExchangeService:
#     VersionRequirement: ~2.0.0
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.pubsub:
        com.devopstar.RobocatContainer:pubsub:1:
          policyDescription: Allows access to publish to devopstar/robocat/thing/meow topic
          operations:
            - aws.greengrass#PublishToTopic
          resources:
            - "*"
Manifests:
- Name: Linux
  Platform:
    os: linux
  Artifacts:
    - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/container.zip"
      Unarchive: ZIP
    # - URI: "docker:536829251200.dkr.ecr.ap-southeast-2.amazonaws.com/robocatcontainer:latest"
  Lifecycle:
    Install:
      RequiresPrivilege: true
      Script: docker load -i {artifacts:decompressedPath}/container/container.tar
    Run:
      RequiresPrivilege: true
      Script: |-
        docker run --rm \
          --name robocatcontainer-zipped \
          --network=host \
          -e SVCUID \
          -e AWS_REGION \
          -e AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT \
          -e AWS_IOT_THING_NAME \
          -v {kernel:rootPath}/ipc.socket:{kernel:rootPath}/ipc.socket \
          robocatcontainer

        # docker run --rm \
        #   --name robocatcontainer-ecr \
        #   --network=host \
        #   -e AWS_CONTAINER_AUTHORIZATION_TOKEN \
        #   -e AWS_CONTAINER_CREDENTIALS_FULL_URI \
        #   -e SVCUID \
        #   -e AWS_REGION \
        #   -e AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT \
        #   -e AWS_IOT_THING_NAME \
        #   -v {kernel:rootPath}/ipc.socket:{kernel:rootPath}/ipc.socket \
        #   robocatcontainer
    Shutdown:
      RequiresPrivilege: true
      Script: |-
        docker stop robocatcontainer-zipped
        # docker stop robocatcontainer-ecr
    Recover:
      RequiresPrivilege: true
      Script: |-
        docker stop robocatcontainer-zipped
        # docker stop robocatcontainer-ecr
